hook.Run("DarkRPStartedLoading")

GM.Version = "1.0.0"
GM.Name = "DerivedRP"
GM.Author = "By Harry, FPtje Falco et al."

DeriveGamemode("darkrp")
DEFINE_BASECLASS("gamemode_darkrp")

GM.DarkRP = BaseClass

hook.Add("PlayerSpawnProp", "BlockProps", function(ply)
    if not ply:IsAdmin() then return false end
end)

hook.Add("PlayerSpawnSENT", "BlockSents", function(ply)
    if not ply:IsAdmin() then return false end
end)

hook.Add("PlayerSpawnSWEP", "BlockSweps", function(ply)
    if not ply:IsAdmin() then return false end
end)

DarkRP.removeChatCommand("000")
DarkRP.removeChatCommand("112")
DarkRP.removeChatCommand("911")
DarkRP.removeChatCommand("999")
DarkRP.removeChatCommand("addagenda")
DarkRP.removeChatCommand("addlaw")
DarkRP.removeChatCommand("addowner")
DarkRP.removeChatCommand("admintell")
DarkRP.removeChatCommand("advert")
DarkRP.removeChatCommand("agenda")
DarkRP.removeChatCommand("ago")
DarkRP.removeChatCommand("braodcast")
DarkRP.removeChatCommand("buy")
DarkRP.removeChatCommand("buyammo")
DarkRP.removeChatCommand("buyshipment")
DarkRP.removeChatCommand("buyvehicle")
DarkRP.removeChatCommand("channel")
DarkRP.removeChatCommand("check")
DarkRP.removeChatCommand("cheque")
DarkRP.removeChatCommand("chief")
DarkRP.removeChatCommand("citizen")
DarkRP.removeChatCommand("cp")
DarkRP.removeChatCommand("cr")
DarkRP.removeChatCommand("credits")
DarkRP.removeChatCommand("demote")
DarkRP.removeChatCommand("drop")
DarkRP.removeChatCommand("demotelicense")
DarkRP.removeChatCommand("forcecancelvote")
DarkRP.removeChatCommand("forcelock")
DarkRP.removeChatCommand("forceown")
DarkRP.removeChatCommand("forceunlock")
DarkRP.removeChatCommand("forceunown")
DarkRP.removeChatCommand("forceunownall")
DarkRP.removeChatCommand("gangster")
DarkRP.removeChatCommand("givelicense")
DarkRP.removeChatCommand("gundealer")
DarkRP.removeChatCommand("hobo")
DarkRP.removeChatCommand("job")
DarkRP.removeChatCommand("jobswitch")
DarkRP.removeChatCommand("lockdown")
DarkRP.removeChatCommand("lottery")
DarkRP.removeChatCommand("makeshipment")
DarkRP.removeChatCommand("mayor")
DarkRP.removeChatCommand("medic")
DarkRP.removeChatCommand("mobboss")
DarkRP.removeChatCommand("moneydrop")
DarkRP.removeChatCommand("placelaws")
DarkRP.removeChatCommand("price")
DarkRP.removeChatCommand("radio")
DarkRP.removeChatCommand("removelaw")
DarkRP.removeChatCommand("removeletters")
DarkRP.removeChatCommand("removeowner")
DarkRP.removeChatCommand("requestlicense")
DarkRP.removeChatCommand("resetlaws")
DarkRP.removeChatCommand("ro")
DarkRP.removeChatCommand("sellalldoors")
DarkRP.removeChatCommand("setlicense")
DarkRP.removeChatCommand("setprice")
DarkRP.removeChatCommand("splitshipment")
DarkRP.removeChatCommand("switchjob")
DarkRP.removeChatCommand("switchjobs")
DarkRP.removeChatCommand("teamunban")
DarkRP.removeChatCommand("title")
DarkRP.removeChatCommand("teamban")
DarkRP.removeChatCommand("togglegroupownable")
DarkRP.removeChatCommand("toggleown")
DarkRP.removeChatCommand("toggleownable")
DarkRP.removeChatCommand("type")
DarkRP.removeChatCommand("unlockdown")
DarkRP.removeChatCommand("unownalldoors")
DarkRP.removeChatCommand("unsetlicense")
DarkRP.removeChatCommand("unwantewd")
DarkRP.removeChatCommand("unwanted")
DarkRP.removeChatCommand("unwarrant")
DarkRP.removeChatCommand("votecp")
DarkRP.removeChatCommand("votemayor")
DarkRP.removeChatCommand("wanted")
DarkRP.removeChatCommand("warrant")
DarkRP.removeChatCommand("write")
DarkRP.removeChatCommand("")
