on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Files
    steps:
      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.FTPUSERNAME }}
          server: node-pl-4.uahost.eu
          port: 2022
          password: ${{ secrets.FTPPASSWORD }}
          local_path: './'
          remote_path: './'